import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
   
    <style jsx>
      {`
      
        `}
    </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="hunting coder blog ,hunter" />
        <link rel="icon" href="/favicon.ico" />
              
      </Head>
     {/* <script src='/n.js' >

     </script> */}

     <nav className={styles.mainnav}>
      <ul>
      <Link href="/"><li >Home</li></Link>
        <Link href="/about"><li>About</li></Link>
        <Link href="/blog"><li>Blog</li></Link>
        <Link href="/contact"><li>Contact</li></Link>
      </ul>
     </nav>
      <main className={styles.main}>

      <span className='myspan'>Hunting Coder</span>
     <img  className={styles.MyImg} src="/img.jpg" width={334} height ={233} />
        <div className='blogs'>
        <h2>popular Blogs</h2>
          <div className='blogItem'>
            <h3>How to learn Java Script in 2023</h3>
            <p>java script use to designe the web</p>
          </div>
          <div className='blogItem'>
            <h3>How to learn Java Script in 2023</h3>
            <p>java script use to designe the web</p>
          </div>
          <div className='blogItem'>
            <h3>How to learn Java Script in 2023</h3>
            <p>java script use to designe the web</p>
          </div>
          
        </div>
      </main>
    </>
  )
}
